### PR TITLE
Rdx rollup addition

### PR DESCRIPTION
**Pull request by jinuthomas**
Signed-off-by: Jinu Joy Thomas <jinu.joy.thomas@in.ibm.com>

### CODE REVIEW

**Review by santoshpuranik — COMMENTED** [review]
This looks good. Do we also need the same for the RDX power and media connector locations? They have location codes, but no LEDs afaik

**Comment by jinuthomas** [comment]
> 

That is already there

**Review by santoshpuranik — APPROVED** [review]

**Comment by santoshpuranik** [comment]
Assuming you have an assoc. JSON change coming?

**Comment by jinuthomas** [comment]
yes

**Pull request merged**
